version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_titanic
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    command: --secure-file-priv=""
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./titanic.csv:/var/lib/mysql-files/titanic.csv
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5